#!/bin/bash

if [[ $# -ne 2 && $# -ne 3 ]]; then
    echo "Usage: $0 <num1> <num2> [-d]"
    exit 1
fi

if [[ ! $1 =~ ^[0-9]+$ || ! $2 =~ ^[0-9]+$ ]]; then
    echo "Error: Both parameters must be numbers."
    exit 1
fi
if [[ $3 == "-d" ]]; then
    echo DELETING $1 $2
    curl -X DELETE http://127.0.0.1:3000/api/event_links -H "Content-Type: application/json" -d '{
      "evt_id_1": '$1',
      "evt_id_2": '$2'
    }'
else
    echo CREATE $1 $2
    curl -X POST http://127.0.0.1:3000/api/event_links -H "Content-Type: application/json" -d '{
      "evt_id_1": '$1',
      "evt_id_2": '$2'
    }'
fi

